### ISSUE TITLE
Is there any way in which we can only display the tags?

### ISSUE THREAD

**Issue by ShaishavGandhi** [qiugang/EditTag#1]
Right now, if I set a taglist, it displays the tags but also adds a cursor along with it to add new tags, which is great. Another use case for this plugin is to only display tags. Is this feature already present? If not I'll be happy to work on it and make a pull request

**Comment by qiugang** [comment]
Thanks,There is a simple way out is to remove EditText view, which is the
last child view of FlowLayout. Wellcome to do a pull request
