### ISSUE TITLE
Several methods cannot be resolved

### ISSUE THREAD

**Issue by joshua-nicholson** [qiugang/EditTag#11]
Hi,

I am trying to setup my app using the exact code in your samples so I can see how this works and then implement it myself. Everything in all of my layouts and the MainActivity.java is the exact same as yours but I am getting several errors about methods that cannot be resolved. These code chunks are below with respective error messages.

```
editTagView.setTagAddCallBack(new EditTag.TagAddCallback() {
            @Override
            public boolean onTagAdd(String tagValue) {
                if ("test1".equals(tagValue)) {
                    return false;
                } else {
                    return true;
                }
            }
        });
```

```
Cannot resolve method setTagAddCallBack()
Cannot resolve method TagAddCallback
```

```
 editTagView.setTagDeletedCallback(new EditTag.TagDeletedCallback() {
            @Override
            public void onTagDelete(String deletedTagValue) {
                Toast.makeText(CreatePostActivity.this, deletedTagValue, Toast.LENGTH_SHORT).show();
            }
        });
```

```
Cannot resolve method setTagDeletedCallback()
Cannot resolve method TagDeletedCallback
```

`editTagView.removeTag("test3");`

`Cannot resolve method removeTag(java.lang.String)`

I was hoping you would be able to figure out what's causing this.

**Comment by qiugang** [comment]
@joshua-nicholson Hi，are you sure you have configured the correct gradle dependencies and the version（1.2.4-beta2）?

**Comment by joshua-nicholson** [comment]
oops wasn't using the beta release, thank you, this resolved my issue.
