### ISSUE TITLE
Programmatiaclly remove tags?

### ISSUE THREAD

**Issue by sirvon** [qiugang/EditTag#8]
Any methods/ways exist to programmatially remove tag from this view?

use case is using this view to hold values that originate from a checkable source.
So that when the value is unchecked in the list, I would like the ability to also cleanly
remove the value from editTag view.

thanks for lib!

**Comment by qiugang** [comment]
You means remove tag by tag value? just like editTagView.removeTag(string value)?

**Comment by sirvon** [comment]
Exactly!!!

**Comment by qiugang** [comment]
@sirvon ok, it will be added next version.

**Comment by qiugang** [comment]
@sirvon it's had been added，please checkout dev branch.sorry for delay😃
